version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:9.6
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=root
     - POSTGRES_DB=users
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
     
  backend:
    build:
      context: .
      dockerfile: docker_backend/Dockerfile
    container_name: backend
    volumes:
      - ./app:/code
    ports:
      - "8082:8082" #PROD
      - "8001:8001" #DEBUG
    depends_on:
      - postgres
   
volumes:
    postgres-data:
        driver: local
